blog/app_blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostList.as_view(), name='post_list'),
    path('filter/<int:action>/', views.post_filter, name='post_filter'),
    path('filter/<str:status>/', views.PostReadFilter.as_view(), name='post_read_filter'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.PostDetail.as_view(), name='post_detail'),
    path('new_post/', views.NewPost.as_view(), name='new_post'),
    path('post_api/', views.PostListAPI.as_view(), name='post_api_list'),
    path('post_api/<int:id>/', views.PostDetailAPI.as_view(), name='post_detail_api'),
    path('swagger_doc/', views.SwaggerDocumentation.as_view(), name='api_documentation'),
    ]

blog/app_users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.UserList.as_view(), name='user_list'),
    path('filter/<int:pk>/', views.UsersFilter.as_view(), name='users_filter'),
    path('user/<username>/', views.UserDetail.as_view(), name='user_detail'),
    path('user/<username>/edit/', views.UserEdit.as_view(), name='user_edit'),
    path('user/<username>/feed/', views.FeedFromFollow.as_view(), name='personal_feed'),
    path('follow/', views.user_follow, name='user_follow'),
    path("registration/", views.RegistrationPage.as_view(), name="registration"),
    path("login/", views.LoginPage.as_view(), name="login"),
    path("logout/", views.LogoutPage.as_view(), name="logout"),
    path('user_api/', views.UserListAPI.as_view(), name='user_list_api'),
    path('user_api/<int:id>/', views.UserDetailAPI.as_view(), name='user_detail_api'),
    path('profile_api/', views.ProfileListAPI.as_view(), name='profile_list_api'),
    path('profile_api/<int:id>/', views.ProfileDetailAPI.as_view(), name='profile_detail_api')
]

blog/blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_blog.urls', namespace='blog')),
    path('users/', include('app_users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/app_users/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    """
        Модель профиля пользователя, является дополнением к модели User,
        и предоставляет дополнительные данные о пользователе.

        Attributes:
        ___________
        * icon - изображение профиля
        * user - соединение с моделью User
        * about - информация о пользователе, которую он может написать
        * birthday - день рождения пользователя
        * followers - поле с отношением многие ко многим, содержит в себе id подписчиков
    """

    icon = models.ImageField(default='default/no_image.png', upload_to='users', blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='user')
    about = models.TextField(max_length=10000, null=True, verbose_name='about')
    birthday = models.DateField(verbose_name='birthday')
    followers = models.ManyToManyField(User, related_name='following',
                                       blank=True)

    class Meta:
        verbose_name = 'profile'
        verbose_name_plural = 'profiles'
        ordering = ('id',)

    def get_absolute_url(self):
        return f'/users/{self.user.username}/'

    def __str__(self):
        return str(self.user.username)

blog/app_users/forms.py
import datetime

from django import forms
from django.contrib.auth.forms import AuthenticationForm


class RegistrationForm(forms.Form):
    """
        Форма регистрации пользователя

        Attributes
        __________
        * icon - изображение профиля (можно не указывать, будет стандартное изображение)
        * username - имя пользователя
        * password - пароль
        * password_confirm - подтверждение пароля
        * about - информация о пользователя
        * birthday - дата рождения пользователя с максимальным значением в 120 лет( вдруг долгожители)
    """
    icon = forms.ImageField(required=False, label='Изображение профиля')
    username = forms.CharField(max_length=25, label='Логин')
    password = forms.CharField(widget=forms.PasswordInput, label='Пароль')
    password_confirm = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput)
    about = forms.CharField(max_length=10000, required=False, label='О себе')
    start_year = datetime.date.today().year - 120
    end_year = datetime.date.today().year - 16
    birthday = forms.DateField(
        label='День рождения',
        widget=forms.SelectDateWidget(
            years=range(start_year, end_year)),
    )


class LoginForm(AuthenticationForm):
    """
        Форма входа в профиль пользователя

        Attibutes
        _________

        * username - имя пользователя
        * password - пароль пользователя
    """
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())


class EditForm(forms.Form):
    """
        Форма редактирования пользователя

        Attributes
        __________

        * about - информация о пользователя
        * birthday - дата рождения пользователя с максимальным значением в 120 лет( вдруг долгожители)
    """
    icon = forms.ImageField(required=False, label='Изображение профиля')
    about = forms.CharField(max_length=10000, required=False, label='О себе')

blog/app_users/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.views import LoginView, LogoutView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth.models import User

from rest_framework.filters import OrderingFilter

from . import forms, models
from app_blog import models as post_models
from app_users import serializers

from rest_framework.generics import ListAPIView, RetrieveUpdateAPIView, RetrieveAPIView


class RegistrationPage(View):
    """
     Представление для отображения и последующей обработки формы регистрации
    """

    def get(self, request):
        form = forms.RegistrationForm
        return render(request, 'users/user/registration.html', {'form': form})

    def post(self, request):
        form = forms.RegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get("password")
            birthday = form.cleaned_data.get('birthday')
            about = form.cleaned_data.get('about')
            icon = form.cleaned_data.get('icon')

            user = models.User.objects.create_user(
                username=username,
                password=password
            )

            models.Profile.objects.create(
                user=user,
                birthday=birthday,
                about=about,
                icon=icon
            )
            new_user = authenticate(
                username=username,
                password=password
            )
            login(request, new_user)
            return redirect("blog:post_list")
        else:
            return render(request, 'users/user/registration.html', {'form': form})


class UserList(View):
    """
        Представление для отображения списка пользователей и количества их постов
    """

    def get(self, request):
        users_list = models.User.objects.annotate(blog_count=Count('blog_post')).order_by('blog_count')
        paginator = Paginator(users_list, 10)
        page = request.GET.get('page')
        pages = paginator.get_page(page)
        return render(
            request, 'users/user/list.html', {
                'users': pages,
                'section': 'users'}
        )


class UsersFilter(View):
    """
        Представление для предоставления списка пользователей по уменьшению/увеличению списка постов
    """

    def get(self, request, pk):
        if pk == 1:
            users_list = models.User.objects.annotate(blog_count=Count('blog_post')).order_by('-blog_count')
        elif pk == 2:
            users_list = models.User.objects.annotate(blog_count=Count('blog_post')).order_by('blog_count')
        paginator = Paginator(users_list, 10)
        page = request.GET.get('page')
        pages = paginator.get_page(page)
        return render(request, 'users/user/list.html', {
            'users': pages,
            'section': 'users'}
                      )


class UserDetail(View):
    """
        Представление для отображения детальной информации о пользователе
    """

    def get(self, request, username):
        user = get_object_or_404(models.User, username=username)
        profile = get_object_or_404(models.Profile, user=user)
        return render(request, 'users/user/detail.html', {
            'profile': profile,
            'section': 'profile'}
                      )


class UserEdit(View):
    """
        Представление для отображения страницы редактирования профиля
    """
    def get(self, request, username):
        form = forms.EditForm
        return render(request, 'users/user/edit.html', {'form': form})

    def post(self, request, username):
        form = forms.EditForm(request.POST, request.FILES)
        if form.is_valid():
            about = form.cleaned_data.get('about')
            icon = form.cleaned_data.get('icon')
            user = request.user.id
            profile = get_object_or_404(models.Profile, user=user)
            profile.about = about
            profile.icon = icon
            profile.save()
            return redirect("users:user_list")
        else:
            return render(request, 'users/user/edit.html', {'form': form})


class LoginPage(LoginView):
    """
        Представлене для отображения страницы для входа в профиль пользователя
    """
    template_name = 'users/user/login.html'
    authentication_form = forms.LoginForm


class LogoutPage(LogoutView):
    """
        Представление для выхода из профиля пользователя
    """
    pass


def user_follow(request):
    """
        Функция-представление для обработки запроса на добавление/удаление подписчика
    """
    if request.method == 'POST':
        follower = models.Profile.objects.get(user=request.user)
        profile_id = request.POST.get('profile_id')
        followed = models.Profile.objects.get(pk=profile_id)
        if follower.user in followed.followers.all():
            followed.followers.remove(follower.user)
        else:
            followed.followers.add(follower.user)
        return redirect('users:user_detail', followed.user.username)
    return redirect('users:user_list')


class FeedFromFollow(View):
    """
        Представление для отображения постов, согласно имеющимся подпискам на того или иного пользователя
    """
    def get(self, request, username):
        username = models.User.objects.get(username=username)
        profiles = models.Profile.objects.filter(followers__in=[username.id])
        profiles = [user.user.id for user in profiles]
        posts = post_models.Post.objects.filter(author__in=profiles, status='published').order_by('-published')
        paginator = Paginator(posts, 10)
        page = request.GET.get('page')
        try:
            posts = paginator.get_page(page)
        except PageNotAnInteger:
            posts = paginator.page(1)
        except EmptyPage:
            posts = paginator.page(paginator.num_pages)
        return render(request, 'users/user/feeds.html', {
            'posts': posts,
            'page': posts,
            'section': 'posts'
        })


class UserListAPI(ListAPIView):
    """
        A view for displaying an endpoint with a list of users.

        Arguments
        _________
        * queryset - responsible for collecting objects inside the database for subsequent display and transmission
        in JSON format;
        * serializer_class - responsible for converting model data into API-friendly format (JSON) and conversely;
        * filter_backends - responsible for filters available on the endpoint
        * ordering_fields - responsible for fields that are affected by the filter
    """

    queryset = User.objects.all().order_by('id')
    serializer_class = serializers.UserSerializer
    filter_backends = [OrderingFilter]
    ordering_fields = ['date_joined', ]


class UserDetailAPI(RetrieveAPIView):
    """
        A view for displaying an endpoint with detail information about user.

        Arguments
        _________
        * queryset - responsible for collecting objects inside the database for subsequent display and transmission
        in JSON format;
        * serializer_class - responsible for converting model data into API-friendly format (JSON) and conversely;

    """

    queryset = User.objects.all().order_by('id')
    serializer_class = serializers.UserSerializer
    lookup_field = 'id'

    def put(self, request, *args, **kwargs):
        """
            The function allows you to create new information in the database or completely replace the existing one

            Fields
            ______
            * "id": int - user's index in database,
            * "is_staff": boolean - true or false (moderator or not),
            * "username": str - just user's nickname,
            * "first_name": str,
            * "last_name": str,
            * "email": str
        """
        return self.update(request, *args, **kwargs)

    def patch(self, request, *args, **kwargs):
        """
            The function allow you to update old information in the database but this information may be partial

            Fields
            ______
            * "id": int - user's index in database,
            * "is_staff": boolean - true or false (moderator or not),
            * "username": str - just user's nickname,
            * "first_name": str,
            * "last_name": str,
            * "email": str
        """
        return self.partial_update(request, *args, **kwargs)


class ProfileListAPI(ListAPIView):
    """
        A view for displaying an endpoint with a list of user's profile.

        Arguments
        _________
        * queryset - responsible for collecting objects inside the database for subsequent display and transmission
        in JSON format;
        * serializer_class - responsible for converting model data into API-friendly format (JSON) and conversely;
        * filter_backends - responsible for filters available on the endpoint
        * ordering_fields - responsible for fields that are affected by the filter
    """

    queryset = models.Profile.objects.all()
    serializer_class = serializers.ProfileSerializer
    filter_backends = [OrderingFilter]
    ordering_fields = ['user__date_joined', ]


class ProfileDetailAPI(RetrieveUpdateAPIView):
    """
        A view for displaying an endpoint with detail information about user's profile.

        Arguments
        _________
        * queryset - responsible for collecting objects inside the database for subsequent display and transmission
        in JSON format;
        * serializer_class - responsible for converting model data into API-friendly format (JSON) and conversely;

    """
    queryset = models.Profile.objects.all()
    serializer_class = serializers.ProfileSerializer
    lookup_field = 'id'

blog/app_users/templates/users/user/detail.html
{% extends 'users/base.html' %}

{% block title %} Профиль {{ profile.user.username }}{% endblock %}

{% block content%}
    <h1>Это профиль {{ profile.user.username }}</h1>
    <div class="profile-info">
        <p>А это фото профиля</p>
        <img src="{{ profile.icon.url }}" alt="icon" height="100" width="100">
        {% with total_followers=profile.followers.count %}
        <br>
        <p>О пользователе: {{ profile.about }}</p>
        <p>День рождения пользователя {{ profile.birthday }}</p>
        <span class="count">
            <span class="total">
               Всего подписчиков: {{ total_followers }}
            </span>
        </span>
        {% if request.user != profile.user %}
            <form action="{% url 'users:user_follow' %}" method="post">
                {% csrf_token %}
                {% if request.user in profile.followers.all %}
                <input type="hidden" name="profile_id" value="{{ profile.id }}">
                <button id="unfollow-btn" type="submit" class="unfollow">unfollow</button>
                {% else %}
                <input type="hidden" name="profile_id" value="{{ profile.id }}">
                <button id="follow-btn" type="submit" class="follow">follow</button>
                {% endif %}
            </form>
        {% endif %}
    </div>
    {% endwith %}
    <p>Добро пожаловать хптьфу</p>
    {% if request.user == profile.user %}
    <a href="{% url 'blog:new_post' %}">Создать пост</a>
    <a href="{% url 'users:personal_feed' request.user %}  ">Новости</a>
    <a href="{% url 'users:user_edit' request.user %}">Редактирование</a>
    <a href="{% url 'users:logout' %}">Выйти из профиля</a>
    {% endif %}
{% endblock %}

blog/app_users/templates/users/user/edit.html
{% extends 'users/base.html' %}

{% block title %}Редактирование{% endblock %}

{% block content %}
  <form method="post" action="" class="login" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
        <p>
            <label for="id_{{field.name}}">{{ field.label }}</label>
            {{ field }}
        </p>
    {% endfor %}
      <p class="edit-submit">
        <button type="submit" class="login-button">Редактировать</button>
      </p>
  </form>
{% endblock %}

blog/app_users/templates/users/user/feeds.html
{% extends 'blog/base.html' %}
{% block title %}Это твоя лента новостей{% endblock %}
{% block content %}
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h2>
        <p class="date">{{ post.author }} опубликовал пост {{ post.published }}</p>
    {% endfor %}
    {% include 'blog/paginator.html' with page=page %}
{% endblock %}

blog/app_users/templates/users/user/list.html
{% extends 'users/base.html' %}

{% block title %}Список пользователей{% endblock %}

{% block content %}
    <a href="{% url 'users:users_filter' pk=1 %}"><button>От большего</button></a>
    <a href="{% url 'users:users_filter' pk=2 %}"><button>От меньшего</button></a>
    {% for profile in users %}
        <p>Пользователь
            <a href="{% url "users:user_detail" profile.username %}">
                {{ profile.username }}
            </a>
            и его количество постов
            {% if profile.blog_count is None %}
            0
            {% else %}
            {{ profile.blog_count }}
            {% endif %}
        </p>
    {% endfor %}
{% endblock %}

blog/app_users/templates/users/user/login.html
{% extends 'users/base.html' %}

{% block title %}Вход{% endblock %}

{% block content %}
    <h1>Вход в профиль</h1>
    {% if form.errors %}
        <p>Неверный логин или пароль, попробуйте снова</p>
    {% else %}
        <p>Используйте форму ниже для входа</p>
    {% endif %}
        <form action="." method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Log in"></p>
        </form>
{% endblock %}

blog/app_users/templates/users/user/logout.html
{% extends 'users/base.html' %}

{% block title %}Выход{% endblock %}

{% block content %}
    <h1>Выход из профиля</h1>
    <p>
        Выход из профиля произведён<br>
        Можете <a href="login">войти в профиль снова </a>
    </p>
{% endblock %}

blog/app_users/templates/users/user/registration.html
{% extends 'users/base.html' %}

{% block title %}Регистрация{% endblock %}

{% block content %}
  <form method="post" action="" class="login" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
        <p>
            <label for="id_{{field.name}}">{{ field.label }}</label>
            {{ field }}
        </p>
    {% endfor %}
      <p class="reg-submit">
        <button type="submit" class="login-button">Регистрация</button>
      </p>
  </form>
{% endblock %}